### ISSUE TITLE
MSFS Pop Out Panel Manager and Freeze possibly cause MSFS20 get freeze

### ISSUE THREAD

**Issue by maddoc2677** [hawkeye-stan/msfs-popout-panel-manager#125]
Hi, since last Fenix A320 update if i use Pop Out Manager and Fenix A320, MSFS20 get freeze just after few seconds or only few minutes after panel got popped out using this mod

Best regards

Enrico

**Comment by maddoc2677** [comment]
I tried to pop out Fenix panels manually without using MSFS Panel Pop Out Manager and i hadn't any freeze . So something it's wrong beetween last release of Panel Pop Out Manager and last release of Fenix

**Comment by hawkeye-stan** [comment]
Sorry I have no way to test Fenix with POPM since I don't have that plane. I tried FBW version of A320 and not getting any freezes. The only recent change in POPM is it now uses the latest version of SimConnect SDK and there could be a conflict with latest Fenix release. Please try to roll back to version 4.1.0 of POPM since it uses an older version of SimConnect SDK.

**Comment by maddoc2677** [comment]
Hi, Thanks for replying. Yeah I confirm no issue with FBW A20NWe absolutely have to find a way to make you test POPM with Fenix :)……as I wrote in GitHub the freeze occur with both last two releases of POPM (4.1.1 and 4.1.0) . The freeze is not temporary, is permanent and make unable to use MSFS Best regardsEnrico Merolla Sent from my iPhone 13 Il giorno 4 ago 2024, alle ore 00:50, Stanley ***@***.***> ha scritto:﻿
Sorry I have no way to test Fenix with POPM since I don't have that plane. I tried FBW version of A320 and not getting any freezes. The only recent change in POPM is it now uses the latest version of SimConnect SDK and there could be a conflict with latest Fenix release. Please try to roll back to version 4.1.0 of POPM since it uses an older version of SimConnect SDK.

**Comment by rammstein1977** [comment]
Here too, problems with Fenix. The program is useless with Fenix

**Comment by hawkeye-stan** [comment]
If the latest Fenix A320 is freezing in both POPM version 4.1.1 and 4.1.0 (few months old version), then the update of SimConnect SDK is probably not the cause since the update happened on POPM version 4.1.1 only. And this issue only happened on latest Fenix and not any other plane, something in the newest Fenix is causing the freeze and I really have no way to figure this out since I don't have this particular paid aircraft. Rolling back to older version of POPM as you have tried does not work either so that is not a workaround. Off the top of my head, I've no idea what could be the cause unless another non-third party paid aircraft is having this issue that I can use to debug the issue. Another possible workaround is after POPM completes the pop out, close POPM so it is no longer running to cause the freeze issue.

**Comment by rammstein1977** [comment]
then the program will not be usable for Fenix at first. I tested pmdg 737 / 777 and IniBuild A300 and there are no problems here

**Comment by hawkeye-stan** [comment]
There are only few things that POPM continues to interact with MSFS or Windows OS after pop out is completed. They're panel tracking, keystroke detection, dynamic LOD, game refocus, and touch panel. Maybe disabling these items in POPM preference could solve the issue if you're not using them. Also disable any touch panel if you've any configured since it interacts with Windows OS to detect touches. Other than that, I'm really at a lost of why the newest Fenix is freezing since I double check that SimConnect SDK is probably not the issue. You can make a copy of POPM aircraft profile to test the change.

![image](https://github.com/user-attachments/assets/0a0bd79e-97d0-4c7b-9448-4d4d3b7ccb65)

![image](https://github.com/user-attachments/assets/118ba94c-edaa-484c-b3b0-f7336812e4bf)

![image](https://github.com/user-attachments/assets/c82ed338-f8be-4033-a65b-dac3015f0ee9)

![image](https://github.com/user-attachments/assets/e8b95e41-1508-4019-a933-1a6bc4d0e6c7)

**Comment by rammstein1977** [comment]
I think it works like this :) I don't need all these extras anyway and for me the problem is solved. In any case, no freeze on the ground for 10 minutes

**Comment by hawkeye-stan** [comment]
Latest tests by user maddoc identify Fenix is the cause of the issue. Manual pop out without POPM still freeze the plane.

**Comment by rammstein1977** [comment]
I'm currently doing my second flight with these settings disabled and it works for me now

**Comment by rammstein1977** [comment]
I have to correct myself.

The first flight went without any problems, the second flight looked good too. But at some point after 4-5 minutes it froze again.

**Comment by maddoc2677** [comment]
Hi some users reported me the same issue also without popping any panel at all.
They said the issue it’s caused , only with Fenix, by latest nvidia driver 560.70, so they solved rolling back the nvidia driver video 
I’ll try it tomorrow and let you know 
Best regards
Enrico

**Comment by macroflight** [comment]
I concur - rolling back the nvidia driver to 552.12 solved the problem for me.

But pop-out windows definitely contributed, I never saw a freeze without them. More complex scenery also seemed to contribute  (e.g OrbX ESSA == freeze, Asobo ESSA == OK).

**Comment by stichtingmeerbach** [comment]
I think I have a FIX!!!

In the Fenix menu outside the sim:

Enable: Use alternative display renderer

Disable: Display VSYNC

Running with latest drivers!

**Comment by stichtingmeerbach** [comment]
Maybe disabling VSYNC in the Fenix menu is enough, did not test that

**Comment by maddoc2677** [comment]
Thanks so much for this great and precious news !! I have absolutely to try . 
best regards 

Enrico

**Comment by Greg320I** [comment]
I have the same issue (Fenix and msfs 2020). Using DX12 causing sim to freeze after some time (few seconds to few minutes). DX11 - without an issues but general performance is worst.
